import dayjs from "dayjs";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import styles from "src/styles/Home.module.css";
import useSWR from "swr";

const fetcher = async (url: string) => {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error("エラーが発生しました");
  }

  return res.json();
};

export const useGetNews = () => {
  const { data, error } = useSWR(
    "https://newsapi.org/v2/everything?q=apple&from=2022-02-26&to=2022-02-26&sortBy=popularity&apiKey=02b730b654a04b6d94b05ff0e6ecfae9",
    fetcher
  );



  return { data, error, isLoading: !data && !error };
}

// export const getStaticProps: GetStaticProps = () => {
//   const { data, error } = useSWR(
//     "https://newsapi.org/v2/everything?q=apple&from=2022-02-26&to=2022-02-26&sortBy=popularity&apiKey=02b730b654a04b6d94b05ff0e6ecfae9",
//     fetcher
//   );
// }

const Home: NextPage = () => {
  const { data, error, isLoading } = useGetNews();

  if (error) return <div>failed to load</div>;
  if (isLoading) return <div>loading...</div>;


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-5xl m-5">Welcome to News Site!</h1>

        <div className="flex flex-wrap justify-around">
          {data
            ? data.articles.map((post) => {
                return (

                  <Link key={post.title} href={post.url}>
                    <a className="flex p-2 m-2 rounded-md border hover:bg-gray-300">
                      <img className="block w-40 h-28" src={post.urlToImage} />
                      <div className="mx-2 w-80">
                        <p>{dayjs(post.publishedAt).format("YYYY-MM-DD")}</p>
                        <h1 className="text-lg">{post.title}</h1>
                        <p>{post.author}</p>
                      </div>
                    </a>
                  </Link>
                );
              })
            : null}
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
